version: '3.1'

services:

  # consume data and put it in elastic
  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.2.2
    ports:
      - "4005:4005"
    environment:
      - ELASTIC_SERVERS=http://elk:9200
    volumes:
      - "${PWD}/pipeline/:/usr/share/logstash/pipeline/"

  # The elastic stack. You know, for search
  elk:
    image: sebp/elk:622
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    environment:
      - LOGSTASH_START=0
    volumes:
      - elk-data:/var/lib/elasticsearch

volumes:                                                              
  elk-data:                                                           


